import React from "react";
import {createRoot} from "react-dom/client";
import {ArrowUpRight, Github, Linkedin, Mail, Download, Code2, Cloud, Sparkles, MapPin} from "lucide-react";
import "./styles.css";

const stats=[{value:"2.5+",label:"years of experience"},{value:"75+",label:"production REST APIs"},{value:"97%",label:"backend test coverage"},{value:"3",label:"enterprise domains"}];

const experience=[
{company:"Tata Consultancy Services",role:"Backend Developer — Scandinavian Airlines (SAS)",period:"Jun 2025 — Present",tag:"Current",description:"Backend and full-stack development on the crew bidding and scheduling platform for Scandinavian Airlines — REST API design, complex business-rule validation, enterprise system integration and relational data modelling.",tech:["TypeScript","Node.js","Fastify","Prisma","PostgreSQL","Azure Service Bus","React","Java","Spring Boot","Jest","SOAP / XML"],points:["Engineered 25+ production REST APIs in Node.js (Fastify) and PostgreSQL powering crew bidding and scheduling workflows, with full request/response schema validation.","Designed and shipped the Bid Period, Bid Window and Priority Management modules with complex business rules, backend validations and workflow constraints.","Led a schema redesign to make business identifiers editable — introduced surrogate keys, authored the backfill migration and updated every dependent reference across services with zero data loss.","Cut long-range query responses from minutes to sub-second by introducing pagination and restructuring deeply nested response payloads.","Owned relational schema design and migrations on Azure PostgreSQL, keeping schema and migration history in sync across the team through to production.","Integrated Azure Service Bus and SOAP services to synchronise crew, roster and operational data across enterprise systems.","Built CodeLens, a Java code visualizer used in the TCS Ignite fresher training programme — AST parsing with injected instrumentation hooks to capture real runtime state and replay program execution step by step for learners.","Maintained ~97% backend line coverage with Jest unit and integration tests, clearing automated review and coverage gates before every merge.","Authored API test reports and UAT evidence used to close tickets and hand over to QA."]},
{company:"CSG Technosol",role:"Associate Developer — Unicon International",period:"Jan 2025 — Jun 2025",description:"Core developer on Unicon International, CSG's in-house multi-currency payment gateway serving merchants, acquirers and sellers — settlement engine, merchant dashboard and live support tooling.",tech:["Python","Django","Django REST Framework","PostgreSQL","JavaScript","WebSockets","Django Channels"],points:["Built the automated settlement processing system end to end — applying MDR, commissions, taxes and per-scheme charge slabs across multi-currency transactions to compute merchant, acquirer and seller payouts without manual intervention.","Developed 20+ secure REST APIs across payment, settlement and reporting dashboard workflows, with centralised exception handling for consistent, predictable error responses.","Cut average API response time from ~900ms to ~300ms and refactored 4 Django modules, removing roughly 30% duplicate code.","Optimised a bulk record-creation flow that ran inserts inside a loop — moved it to batched bulk operations, cutting processing time from ~30s to ~7s (~77% faster).","Architected and launched in-app live chat support on the web platform, connecting merchants directly with the technical and transaction support teams over WebSockets and Django Channels — the feature was carried forward by the team after my handover.","Implemented role-based access control across merchant, acquirer and internal support roles using middleware and custom decorators."]},
{company:"FaithCode Technologies",role:"Junior Software Engineer",period:"Feb 2024 — Jan 2025",description:"Built backend and frontend functionality for an Applicant Tracking System and recruitment workflows.",tech:["Python","Django","React","REST APIs","SQL","GPT"],points:["Developed 30+ Django REST APIs across candidate, interview and placement workflows.","Implemented GPT-based job-description parsing into structured job data.","Built React components, frontend functionality and automated email workflows."]}
];
const projects=[
{title:"Airline Crew Bidding & Scheduling",icon:"✈️",description:"Enterprise platform for airline crew bidding and scheduling — rule-driven validation, seniority-based bidding priority, role-based administration and event-driven synchronisation with enterprise systems.",tech:["TypeScript","Node.js","Fastify","PostgreSQL","Azure Service Bus","SOAP"]},
{title:"CodeLens — Java Code Visualizer",icon:"☕",description:"An interactive Java execution visualizer built at TCS for the Ignite fresher training programme. Parses submitted Java source into an AST, injects instrumentation hooks and state-tracking injectors directly into the code, compiles the instrumented source with the Java compiler, and replays real runtime state as an animated step-by-step walkthrough with prev/next controls. Longer, more complex programs emit proportionally richer traces — routinely 70K+ lines of structured JSON, scaling into the hundreds of thousands.",tech:["Java","Spring Boot","Java AST Parser","Bytecode Instrumentation","JSON","REST APIs"]},
{title:"Applicant Tracking System",icon:"👥",description:"Multi-tenant recruitment platform covering candidate onboarding, job management, interviews, document parsing and placement workflows.",tech:["Python","Django","DRF","React","SQL","GPT"]},
{title:"Unicon International Payment Gateway",icon:"💳",description:"Multi-currency payment gateway for merchants, acquirers and sellers. Automated settlement engine applying MDR, commissions and charge slabs, reporting dashboards with role-based access, and real-time in-app live chat support over WebSockets.",tech:["Python","Django","DRF","PostgreSQL","WebSockets","Django Channels"]}
];
const skills={"Backend":["Node.js","Fastify","TypeScript","Python","Django","Django REST Framework","REST APIs"],"Java & Spring":["Java","Spring Boot","Spring MVC","Spring Data JPA","Hibernate","Spring Security","Maven","JUnit"],"Frontend":["React.js","JavaScript","HTML","CSS","jQuery"],"Data":["PostgreSQL","MySQL","SQL","Prisma ORM","Schema Migrations"],"Cloud & Integration":["AWS","Azure","Azure Service Bus","SOAP","XML","JSON"],"Engineering":["Microservices","RBAC","Middleware","WebSockets","Docker","Git","CI/CD","Jest","Unit Testing"],"AI & GenAI":["GitHub Copilot","AI Agents","GPT Integration","Prompt Engineering"]};

const Chips=({items})=><div className="chips">{items.map(x=><span key={x}>{x}</span>)}</div>;

function App(){
return <div className="app">
<header className="nav"><a className="brand" href="#top">AK<span>.</span></a><nav><a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#skills">Skills</a><a href="#contact">Contact</a></nav><a className="nav-cta" href="mailto:averma.sre@gmail.com">Let's talk <ArrowUpRight size={16}/></a></header>
<main id="top">
<section className="hero section"><div className="hero-copy"><div className="eyebrow"><span/>Backend-focused Full Stack Developer</div><h1>Building reliable<br/><em>software systems.</em></h1><p className="hero-text">I'm Aakash Kumar, a software developer with 2.5+ years of professional experience building backend-heavy full-stack applications with Node.js, TypeScript, Python, Java, React and PostgreSQL — currently shipping an airline crew bidding platform for Scandinavian Airlines.</p><div className="hero-actions"><a className="primary-btn" href="#projects">Explore my work <ArrowUpRight size={18}/></a><a className="secondary-btn" href="/Aakash_Kumar_Resume.pdf" download="Aakash_Kumar_Resume.pdf"><Download size={17}/> Resume</a></div><div className="socials"><a href="https://www.linkedin.com/in/avermasre" target="_blank" rel="noreferrer"><Linkedin size={18}/>LinkedIn</a><a href="https://github.com/averma0001" target="_blank" rel="noreferrer"><Github size={18}/>GitHub</a><a href="https://leetcode.com/avermasre" target="_blank" rel="noreferrer"><Code2 size={18}/>LeetCode</a></div></div>
<div className="hero-visual"><div className="glow"/><div className="code-card"><div className="code-top"><span/><span/><span/><small>backend.ts</small></div><pre>{`const developer = {
  name: "Aakash Kumar",
  focus: "Backend",
  stack: [
    "Node.js", "TypeScript",
    "Java", "Spring Boot",
    "Python", "PostgreSQL"
  ],
  mindset: "Build. Learn. Improve."
};`}</pre></div><div className="floating-card"><Sparkles size={17}/><div><strong>2.5+ years</strong><small>professional experience</small></div></div></div></section>

<section className="section stats-section"><div className="stats">{stats.map(s=><div className="stat" key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div></section>

<section id="about" className="section compact-section"><div className="section-label">01 / About</div><div className="about-grid"><h2>Backend is my strength.<br/><span>Full-stack is my range.</span></h2><div><p>I work primarily on backend services, APIs, business logic, data modelling and migrations, while staying comfortable contributing across the frontend.</p><p>Today I build rule-driven airline systems in TypeScript and Node.js on PostgreSQL and Azure, with earlier production experience in Python/Django and hands-on work in Java and Spring Boot. Integrations, microservices, testing discipline and AI-assisted development run through all of it.</p></div></div></section>

<section id="experience" className="section"><div className="section-label">02 / Experience</div><div className="timeline">{experience.map((item,i)=><article className="experience" key={item.company}><div className="timeline-dot">{String(i+1).padStart(2,"0")}</div><div className="exp-main"><div className="exp-head"><div><h3>{item.company}{item.tag&&<span className="tag">{item.tag}</span>}</h3><p>{item.role}</p></div><time>{item.period}</time></div><p className="muted">{item.description}</p><ul>{item.points.map(p=><li key={p}>{p}</li>)}</ul><Chips items={item.tech}/></div></article>)}</div></section>

<section id="projects" className="section"><div className="section-label">03 / Selected work</div><div className="project-grid">{projects.map((p,i)=><article className="project-card" key={p.title}><div className="project-top"><span className="project-icon">{p.icon}</span><span>0{i+1}</span></div><h3>{p.title}</h3><p>{p.description}</p><Chips items={p.tech}/></article>)}</div></section>

<section id="skills" className="section"><div className="section-label">04 / Toolkit</div><div className="skills-grid">{Object.entries(skills).map(([g,items])=><article className="skill-group" key={g}><h3>{g}</h3><Chips items={items}/></article>)}</div></section>

<section className="section credentials"><div className="credential-card"><Cloud size={24}/><div><strong>AWS Certified Developer — Associate</strong><span>DVA-C02</span></div></div><div className="credential-card"><Sparkles size={24}/><div><strong>Claude Certified Architect — Professional</strong><span>Anthropic</span></div></div></section>

<section id="contact" className="section contact"><div className="section-label">05 / Contact</div><div className="contact-box"><div><p className="eyebrow"><span/>Have a role or project?</p><h2>Let's build something<br/><em>worth shipping.</em></h2></div><div className="contact-links"><a href="mailto:averma.sre@gmail.com"><Mail size={18}/>averma.sre@gmail.com<ArrowUpRight size={16}/></a><a href="https://www.linkedin.com/in/avermasre" target="_blank" rel="noreferrer"><Linkedin size={18}/>LinkedIn<ArrowUpRight size={16}/></a><a href="https://github.com/averma0001" target="_blank" rel="noreferrer"><Github size={18}/>GitHub<ArrowUpRight size={16}/></a></div></div></section>
</main>
<footer><span>© {new Date().getFullYear()} Aakash Kumar</span><span><MapPin size={14}/>India</span><span>Built with React</span></footer>
</div>}

createRoot(document.getElementById("root")).render(<App/>);